name: Commit

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Crear archivo nuevo
        run: |
          echo "Hola mundo desde GitHub Actions" > saludo.txt

      - name: Commit y push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add saludo.txt
          git commit -m "Agrego saludo.txt automáticamente"
          git push origin HEAD:${GITHUB_REF##*/}


#    git config user.name "${{ github.actor }}"
#    git config user.email "${{ github.actor }}@users.noreply.github.com"
#    git add saludo.txt
#    git commit -m "Commit automático lanzado por ${{ github.actor }}"
